In [3]:
import pandas as pd

df = pd.read_json("apartmentscom-raw.json")
df2 = pd.read_csv("zillow-raw.csv")

In [ ]:
df.head()

,listingId,url,streetAddress,fullAddress,price,priceRanges,details,propertyType,propertyName,imageUrl,...,verified,scores,fees,petFees,parkingFees,models,structuredData,images,moreDetails,listingUrl
0,kf1ky79,https://www.apartments.com/1009-s-2nd-st-champ...,1009 S 2nd St,1009 S 2nd St Champaign IL 61820 US,$910 - $795,"[{'beds': '2 Beds', 'price': '$910'}, {'beds':...","2 Beds, 4 Beds",Apartment,1009 S 2nd St,https://images1.apartments.com/i2/mDeD4SXfS5_B...,...,,{},[],[],[],[{'modelName': '2 Bedroom - Pre-Leasing August...,"{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...","{'name': '1009 S 2nd St', 'address': {'cc': 'U...",NaN
1,04et261,https://www.apartments.com/the-landing-at-lege...,4503 Legends Dr,4503 Legends Dr Champaign IL 61822 US,"$1,739+ - $2,084+","[{'beds': '1 Bed', 'price': '$1,739+'}, {'beds...","1 Bed, 2 Beds",Apartment,The Landing at Legends | Specials Available,https://images1.apartments.com/i2/Fdhw1w9LbRXr...,...,Verified Listing,{},[],[],[],"[{'modelName': 'The Monaco', 'rentLabel': '$1,...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...",{'name': 'The Landing at Legends | Specials Av...,https://www.thelandingatlegends.com/?utm_sourc...
2,jcvk767,https://www.apartments.com/maywood-apartments-...,51 E John St,51 E John St Champaign IL 61820 US,$985 - $995 - $975,"[{'beds': '2 Beds', 'price': '$985'}, {'beds':...","2 Beds, 3 Beds, 4 Beds",Apartment,Maywood Apartments,https://images1.apartments.com/i2/EFJOEYomIt-3...,...,Verified Listing,{},[],[],[],"[{'modelName': '2x1', 'rentLabel': '$985 ...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...","{'name': 'Maywood Apartments', 'address': {'cc...",NaN
3,vn1k7tf,https://www.apartments.com/202-e-green-st-by-b...,202 E Green St,202 E Green St Champaign IL 61820 US,"$1,550 - $875","[{'beds': '1 Bed', 'price': '$1,550'}, {'beds'...","1 Bed, 4 Beds",Apartment,202 E. Green St by Bankier Apartments,https://images1.apartments.com/i2/U8NJf1As7B4Q...,...,,{},[],[],[],"[{'modelName': '1BR/1BA', 'rentLabel': '$1,550...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...",{'name': '202 E. Green St by Bankier Apartment...,NaN
4,vntmh0d,https://www.apartments.com/latitude-student-ho...,608 E University Ave,608 E University Ave Champaign IL 61820 US,"$1,539+ - $1,049+ - $929+","[{'beds': '1 Bed', 'price': '$1,539+'}, {'beds...","1 Bed, 2 Beds, 4 Beds",Apartment,Latitude | Student Housing,https://images1.apartments.com/i2/UYF1jvC59BVS...,...,Verified Listing,{},[],[],[],"[{'modelName': '1BR', 'rentLabel': '$1,539 – $...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...","{'name': 'Latitude | Student Housing', 'addres...",NaN

In [5]:
df2

,address,addressCity,addressState,addressStreet,addressZipcode,area,availabilityCount,availabilityDate,baths,beds,...,units/0/price,units/0/roomForRent,units/1/beds,units/1/price,units/1/roomForRent,units/2/beds,units/2/price,units/2/roomForRent,zestimate,zpid
0,"402 S Busey Ave, Urbana, IL 61801",Urbana,IL,402 S Busey Ave,61801,2900.0,NaN,2026-08-15 00:00:00,3.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,284500.0,3238420
1,"1008 S Busey Ave APT 5, Urbana, IL 61801",Urbana,IL,1008 S Busey Ave APT 5,61801,900.0,NaN,NaN,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2094965487
2,"808 Springfield Ave #2, Urbana, IL 61801",Urbana,IL,808 Springfield Ave #2,61801,NaN,NaN,2026-08-17 00:00:00,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,461332050
3,"707 W Elm St #4, Urbana, IL 61801",Urbana,IL,707 W Elm St #4,61801,850.0,NaN,NaN,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2060538913
4,"1010 Springfield Ave #304, Urbana, IL 61801",Urbana,IL,1010 Springfield Ave #304,61801,NaN,NaN,2026-04-10 00:00:00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,457943142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,"903 N Lincoln Ave, Urbana, IL",Urbana,IL,903 N Lincoln Ave # 10499495,61801,NaN,4.0,NaN,NaN,NaN,...,"$1,950+",False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.12029--88.21991
76,"1105 W Main St, Urbana, IL",Urbana,IL,1105 W Main St # 17951808,61801,NaN,3.0,NaN,NaN,NaN,...,$450+,False,3.0,$499+,False,NaN,NaN,NaN,NaN,40.11426--88.22303
77,"712 W Illinois, 712 W Illinois St #2, Urbana, ...",Urbana,IL,712 W Illinois St #2,61801,NaN,NaN,NaN,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2077122133
78,"311 E Daniel St, 311 E Daniel St, Champaign, I...",Champaign,IL,311 E Daniel St #11209871,61820,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,352582633
79,"705 W Main St, Urbana, IL",Urbana,IL,705 W Main St # 19755568,61801,NaN,3.0,NaN,NaN,NaN,...,$815+,False,1.0,$895+,False,3.0,$485+,False,NaN,40.113834--88.21651

### utilities 파싱

In [ ]:
def extract_utilities(fee):
    try:
        utilities = fee['UtilitiesAndEssentials']
        return [u['FeeDisplayName'] for u in utilities]
    except:
        return []

df['utilities'] = df['transparentFee'].apply(extract_utilities)

In [ ]:
def estimate_cost(row):
    base = row['listingMinRent']
    
    # 단순 예시
    if 'High Speed Internet Access' not in row['utilities']:
        base += 25
    if 'Garbage Service' not in row['utilities']:
        base += 20
        
    return base

df['estimated_total_cost'] = df.apply(estimate_cost, axis=1)

df.head()

,listingId,url,streetAddress,fullAddress,price,priceRanges,details,propertyType,propertyName,imageUrl,...,fees,petFees,parkingFees,models,structuredData,images,moreDetails,listingUrl,utilities,estimated_total_cost
0,kf1ky79,https://www.apartments.com/1009-s-2nd-st-champ...,1009 S 2nd St,1009 S 2nd St Champaign IL 61820 US,$910 - $795,"[{'beds': '2 Beds', 'price': '$910'}, {'beds':...","2 Beds, 4 Beds",Apartment,1009 S 2nd St,https://images1.apartments.com/i2/mDeD4SXfS5_B...,...,[],[],[],[{'modelName': '2 Bedroom - Pre-Leasing August...,"{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...","{'name': '1009 S 2nd St', 'address': {'cc': 'U...",NaN,"[High Speed Internet Access, Recycling, Garbag...",795
1,04et261,https://www.apartments.com/the-landing-at-lege...,4503 Legends Dr,4503 Legends Dr Champaign IL 61822 US,"$1,739+ - $2,084+","[{'beds': '1 Bed', 'price': '$1,739+'}, {'beds...","1 Bed, 2 Beds",Apartment,The Landing at Legends | Specials Available,https://images1.apartments.com/i2/Fdhw1w9LbRXr...,...,[],[],[],"[{'modelName': 'The Monaco', 'rentLabel': '$1,...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...",{'name': 'The Landing at Legends | Specials Av...,https://www.thelandingatlegends.com/?utm_sourc...,[],1784
2,jcvk767,https://www.apartments.com/maywood-apartments-...,51 E John St,51 E John St Champaign IL 61820 US,$985 - $995 - $975,"[{'beds': '2 Beds', 'price': '$985'}, {'beds':...","2 Beds, 3 Beds, 4 Beds",Apartment,Maywood Apartments,https://images1.apartments.com/i2/EFJOEYomIt-3...,...,[],[],[],"[{'modelName': '2x1', 'rentLabel': '$985 ...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...","{'name': 'Maywood Apartments', 'address': {'cc...",NaN,[Valet Trash],1020
3,vn1k7tf,https://www.apartments.com/202-e-green-st-by-b...,202 E Green St,202 E Green St Champaign IL 61820 US,"$1,550 - $875","[{'beds': '1 Bed', 'price': '$1,550'}, {'beds'...","1 Bed, 4 Beds",Apartment,202 E. Green St by Bankier Apartments,https://images1.apartments.com/i2/U8NJf1As7B4Q...,...,[],[],[],"[{'modelName': '1BR/1BA', 'rentLabel': '$1,550...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...",{'name': '202 E. Green St by Bankier Apartment...,NaN,[],920
4,vntmh0d,https://www.apartments.com/latitude-student-ho...,608 E University Ave,608 E University Ave Champaign IL 61820 US,"$1,539+ - $1,049+ - $929+","[{'beds': '1 Bed', 'price': '$1,539+'}, {'beds...","1 Bed, 2 Beds, 4 Beds",Apartment,Latitude | Student Housing,https://images1.apartments.com/i2/UYF1jvC59BVS...,...,[],[],[],"[{'modelName': '1BR', 'rentLabel': '$1,539 – $...","{'product': {'@context': 'https://schema.org',...","[{'@type': 'https://schema.org/ImageObject', '...","{'name': 'Latitude | Student Housing', 'addres...",NaN,"[Short Term Fee, Building Protection Fee, Util...",974

In [ ]:
df_clean = df[[
    'propertyName',
    'fullAddress',
    'listingCity',
    'listingNeighborhood',
    'listingMinRent',
    'listingMaxRent',
    'beds',
    'bathrooms',
    'location',
    'amenities',
    'transparentFee',
    'rentals'
]].copy()

df_clean.head()

,propertyName,fullAddress,listingCity,listingNeighborhood,listingMinRent,listingMaxRent,beds,bathrooms,location,amenities,transparentFee,rentals
0,1009 S 2nd St,1009 S 2nd St Champaign IL 61820 US,Champaign,Downtown Champaign,795,910,4,"{'min': 1, 'max': 2}","{'latitude': 40.10569, 'longitude': -88.23729}","[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '3kgm4qg', 'RentalType': 1, 'Mo..."
1,The Landing at Legends | Specials Available,4503 Legends Dr Champaign IL 61822 US,Champaign,,1739,2119,2,"{'min': 1, 'max': 2}","{'latitude': 40.07081, 'longitude': -88.31763}","[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'z52z7cw', 'RentalType': 1, 'Mo..."
2,Maywood Apartments,51 E John St Champaign IL 61820 US,Champaign,Downtown Champaign,975,995,4,"{'min': 1, 'max': 2}","{'latitude': 40.10863, 'longitude': -88.23987}","[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'e5whgfn', 'RentalType': 1, 'Mo..."
3,202 E. Green St by Bankier Apartments,202 E Green St Champaign IL 61820 US,Champaign,Campustown IL,875,1550,4,"{'min': 1, 'max': 3}","{'latitude': 40.11066, 'longitude': -88.23668}","[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'gwl5bzy', 'RentalType': 1, 'Mo..."
4,Latitude | Student Housing,608 E University Ave Champaign IL 61820 US,Champaign,Downtown Champaign,929,1999,4,"{'min': 1, 'max': 4}","{'latitude': 40.11666, 'longitude': -88.22965}","[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'des617k', 'RentalType': 1, 'Mo..."

In [ ]:
def extract_unit_types(rentals):
    try:
        return list(set([r['Beds'] for r in rentals]))
    except:
        return []

df_clean['bed_types'] = df_clean['rentals'].apply(extract_unit_types)
df_clean.head()

,propertyName,fullAddress,listingCity,listingNeighborhood,listingMinRent,listingMaxRent,beds,bathrooms,location,amenities,transparentFee,rentals,bed_types
0,1009 S 2nd St,1009 S 2nd St Champaign IL 61820 US,Champaign,Downtown Champaign,795,910,4,"{'min': 1, 'max': 2}","{'latitude': 40.10569, 'longitude': -88.23729}","[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '3kgm4qg', 'RentalType': 1, 'Mo...","[2, 4]"
1,The Landing at Legends | Specials Available,4503 Legends Dr Champaign IL 61822 US,Champaign,,1739,2119,2,"{'min': 1, 'max': 2}","{'latitude': 40.07081, 'longitude': -88.31763}","[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'z52z7cw', 'RentalType': 1, 'Mo...","[1, 2]"
2,Maywood Apartments,51 E John St Champaign IL 61820 US,Champaign,Downtown Champaign,975,995,4,"{'min': 1, 'max': 2}","{'latitude': 40.10863, 'longitude': -88.23987}","[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'e5whgfn', 'RentalType': 1, 'Mo...","[2, 3, 4]"
3,202 E. Green St by Bankier Apartments,202 E Green St Champaign IL 61820 US,Champaign,Campustown IL,875,1550,4,"{'min': 1, 'max': 3}","{'latitude': 40.11066, 'longitude': -88.23668}","[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'gwl5bzy', 'RentalType': 1, 'Mo...","[1, 4]"
4,Latitude | Student Housing,608 E University Ave Champaign IL 61820 US,Champaign,Downtown Champaign,929,1999,4,"{'min': 1, 'max': 4}","{'latitude': 40.11666, 'longitude': -88.22965}","[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'des617k', 'RentalType': 1, 'Mo...","[1, 2, 4]"

In [ ]:
df_clean['lat'] = df_clean['location'].apply(lambda x: x['latitude'])
df_clean['lng'] = df_clean['location'].apply(lambda x: x['longitude'])

In [ ]:
def extract_utilities(fee):
    try:
        return [u['FeeDisplayName'] for u in fee['UtilitiesAndEssentials']]
    except:
        return []

df_clean['utilities'] = df_clean['transparentFee'].apply(extract_utilities)

In [ ]:
def simplify_amenities(amenities):
    try:
        return [item for group in amenities for item in group['value']]
    except:
        return []

df_clean['amenities_simple'] = df_clean['amenities'].apply(simplify_amenities)

In [ ]:
def has_utility(row, keyword):
    return any(keyword.lower() in u.lower() for u in row['utilities'])

In [ ]:
def estimate_total_cost(row):
    base = row['listingMinRent']
    
    # utilities 없으면 추가
    if not has_utility(row, "internet"):
        base += 25
        
    if not has_utility(row, "garbage"):
        base += 20
        
    if not has_utility(row, "recycling"):
        base += 10
        
    # electricity / gas는 보통 안 나와서 기본 추가
    base += 50  # 평균값 (대충 잡은 것)
    
    return base

In [ ]:
df_clean['estimated_total_cost (per person)'] = df_clean.apply(estimate_total_cost, axis=1)

In [ ]:
df_clean['bath_min'] = df_clean['bathrooms'].apply(lambda x: x['min'] if isinstance(x, dict) else None)
df_clean['bath_max'] = df_clean['bathrooms'].apply(lambda x: x['max'] if isinstance(x, dict) else None)

df_clean = df_clean.drop(columns=['bathrooms'], errors='ignore')

In [ ]:
df_clean = df_clean.drop(columns=['beds', 'location'])
df_clean

,propertyName,fullAddress,listingCity,listingNeighborhood,listingMinRent,listingMaxRent,amenities,transparentFee,rentals,bed_types,lat,lng,utilities,amenities_simple,estimated_total_cost (per person),bath_min,bath_max
0,1009 S 2nd St,1009 S 2nd St Champaign IL 61820 US,Champaign,Downtown Champaign,795,910,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '3kgm4qg', 'RentalType': 1, 'Mo...","[2, 4]",40.10569,-88.23729,"[High Speed Internet Access, Recycling, Garbag...","[Furnished Units Available, Controlled Access,...",845,1.0,2.0
1,The Landing at Legends | Specials Available,4503 Legends Dr Champaign IL 61822 US,Champaign,,1739,2119,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'z52z7cw', 'RentalType': 1, 'Mo...","[1, 2]",40.07081,-88.31763,[],"[Pool, Fitness Center, Elevator, Clubhouse, Wa...",1844,1.0,2.0
2,Maywood Apartments,51 E John St Champaign IL 61820 US,Champaign,Downtown Champaign,975,995,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'e5whgfn', 'RentalType': 1, 'Mo...","[2, 3, 4]",40.10863,-88.23987,[Valet Trash],"[Fitness Center, Furnished Units Available, El...",1080,1.0,2.0
3,202 E. Green St by Bankier Apartments,202 E Green St Champaign IL 61820 US,Champaign,Campustown IL,875,1550,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'gwl5bzy', 'RentalType': 1, 'Mo...","[1, 4]",40.11066,-88.23668,[],"[Fitness Center, Furnished Units Available, El...",980,1.0,3.0
4,Latitude | Student Housing,608 E University Ave Champaign IL 61820 US,Champaign,Downtown Champaign,929,1999,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'des617k', 'RentalType': 1, 'Mo...","[1, 2, 4]",40.11666,-88.22965,"[Short Term Fee, Building Protection Fee, Util...","[Pool, Fitness Center, Furnished Units Availab...",1034,1.0,4.0
5,BRAND NEW The Station @ 505 S Fifth,505 S 5th St Champaign IL 61820 US,Champaign,Campustown IL,950,1950,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'wve940h', 'RentalType': 1, 'Mo...","[0, 1, 3, 4]",40.11200,-88.23245,[],"[Fitness Center, Elevator, Clubhouse, Controll...",1055,1.0,4.0
6,Pacifica on Green,28 E Green St Champaign IL 61820 US,Champaign,Midtown Champaign,949,2409,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'wvybhhk', 'RentalType': 1, 'Mo...","[1, 2, 3, 4]",40.11059,-88.24144,[],"[Fitness Center, Furnished Units Available, El...",1054,1.0,3.0
7,Alley Lofts at The Pilot,312 S Prairie St Champaign IL 61820 US,Champaign,Downtown Champaign,1530,2320,"[{'title': 'Community Amenities', 'value': ['R...",None,"[{'RentalKey': '0vxz0e0', 'RentalType': 1, 'Mo...","[0, 2]",40.11349,-88.24809,[],"[Recycling, Community-Wide WiFi, Trash Pickup ...",1635,1.0,1.0
8,611 S State St,611 S State St Champaign IL 61820 US,Champaign,Downtown Champaign,1495,1795,"[{'title': 'Community Amenities', 'value': ['L...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'yd9wt3s', 'RentalType': 1, 'Mo...","[1, 2]",40.10913,-88.24704,"[Utility - Water, Trash, Sewer, Internet]","[Laundry Facilities, Furnished Units Available...",1575,1.0,1.0
9,Onyx Apartments,1321 N Lincoln Ave Urbana IL 61801 US,Urbana,,635,1655,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'zzdy79w', 'RentalType': 1, 'Mo...","[1, 2, 4]",40.12466,-88.22132,[],"[Pool, Fitness Center, Furnished Units Availab...",740,1.0,2.0
10,The Whitney Apartments,1601 E Florida Ave Urbana IL 61802 US,Urbana,,1425,1479,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'wj1hx7h', 'RentalType': 1, 'Mo...","[2, 3]",40.09740,-88.18937,"[Resident Benefit Package, Resident Benefit Pa...","[Pool, Fitness Center, Furnished Units Availab...",1530,2.0,3.0
11,Parkview Apartments Available Summer 2026,412 W Church St Champaign IL 61820 US,Champaign,Downtown Champaign,1395,1395,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'w6qpz5j', 'RentalType': 1, 'Mo...",[1],40.11847,-88.24987,"[Utility Usage Fee, Utility - Electric]","[Furnished Units Available, Controlled Access,...",1500,1.0,1.0
12,The Legends Apartments | Specials Available,4422 Nicklaus Dr Champaign IL 61822 US,Champaign,,1360,1915,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'dq3swkh', 'RentalType': 1, 'Mo...","[1, 2, 3]",40.07461,-88.31757,[],"[Pool, Fitness Center, Clubhouse, Recycling, W...",1465,1.0,2.0
13,Southwood Crossing,1915 S Mattis Ave Champaign IL 61821 US,Champaign,,1425,2099,"[{'title': 'Community Amenities', 'value': ['C...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'zmfn9ty', 'RentalType': 1, 'Mo...","[1, 2, 3]",40.09148,-88.27738,[Utility Service Fee],"[Controlled Access, EV Charging, Renters Insur...",1530,1.0,2.0
14,Hunters Pond Apartment Homes,2717 Hunters Pond Run Champaign IL 61820 US,Champaign,,1236,2033,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '2c6vyn8', 'RentalType': 1, 'Mo...","[1, 2]",40.14828,-88.24468,[],"[Pool, Fitness Center, Furnished Units Availab...",1341,1.0,2.0
15,Tuscany Ridge Townhomes,918-1188 Pomona Dr Champaign IL 61822 US,Champaign,,1195,1375,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'w51zbqh', 'RentalType': 1, 'Mo...","[2, 3]",40.12538,-88.29394,[Administrative Fee],"[Playground, Walking/Biking Trails, Public Tra...",1300,2.5,2.5
16,Town & Country Apartments,1032 Kerr Ave E Urbana IL 61802 US,Urbana,,847,1711,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'tybx1jb', 'RentalType': 1, 'Mo...","[1, 2]",40.12222,-88.19665,[Technology Rent],"[Pool, Fitness Center, Laundry Facilities, Pla...",952,1.0,2.0
17,Capstone Quarters,1901 N Lincoln Ave Urbana IL 61801 US,Urbana,,465,660,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '3vhwngf', 'RentalType': 1, 'Mo...","[2, 3, 4]",40.12974,-88.22121,"[Administrative Fee - $10.00 per month, Utilit...","[Pool, Fitness Center, Furnished Units Availab...",570,2.0,4.0
18,Twin Oaks,2415-2435 W Bradley Ave Champaign IL 61821 US,Champaign,,875,875,"[{'title': 'Community Amenities', 'value': ['L...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'lp9s30e', 'RentalType': 1, 'Mo...",[1],40.12643,-88.28911,[],"[Laundry Facilities, 24 Hour Access, Trash Pic...",980,1.0,1.0
19,The Linc Apartments,1601 N Lincoln Ave Urbana IL 61801 US,Urbana,,675,885,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'd30ljbj', 'RentalType': 1, 'Mo...","[2, 3, 4]",40.12814,-88.22014,[],"[Pool, Fitness Center, Furnished Units Availab...",780,2.0,4.0
20,Westgate Apartments,1600 W Bradley Ave Champaign IL 61821 US,Champaign,,775,1200,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'verjn9e', 'RentalType': 1, 'Mo...","[1, 2]",40.12864,-88.27297,[],"[Pool, Fitness Center, Laundry Facilities, Pla...",880,1.0,1.0
21,519 E. Green St by Bankier Apartments,519 E Green St Champaign IL 61820 US,Champaign,Campustown IL,1125,1125,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'n5jh8zm', 'RentalType': 1, 'Mo...",[2],40.11010,-88.23063,[],"[Fitness Center, Furnished Units Available, El...",1230,2.0,2.0
22,Baytowne Apartments,1000 Baytowne Dr Champaign IL 61822 US,Champaign,,1080,2345,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'r5jmh80', 'RentalType': 1, 'Mo...","[1, 2]",40.14082,-88.26269,[],"[Pool, Fitness Center, Clubhouse, Grill, Dishw...",1185,1.0,2.5
23,Lofts 54,54 E Chalmers St Champaign IL 61820 US,Champaign,Downtown Champaign,875,3600,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'j8tnyt5', 'RentalType': 1, 'Mo...",[4],40.10683,-88.23978,[],"[Furnished Units Available, Roof Terrace, Recy...",980,2.0,2.0
24,Campus Oaks,502 W Green St Urbana IL 61801 US,Urbana,,750,750,"[{'title': 'Community Amenities', 'value': ['G...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'pp1gnes', 'RentalType': 1, 'Mo...",[4],40.11085,-88.21365,[],"[Grill, Bicycle Storage, Individual Leases Ava...",855,2.0,2.0
25,The Cottages at Lake Falls,70 Airport Rd Savoy IL 61874 US,Savoy,,2600,2600,"[{'title': 'Community Amenities', 'value': ['C...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'qfe9pwx', 'RentalType': 1, 'Mo...",[2],40.04137,-88.25085,[High Speed Internet Access],"[Controlled Access, 24 Hour Access, Pet Play A...",2680,2.0,2.0
26,Park Vista,2408 High View Ct Champaign IL 61822 US,Champaign,,895,1100,"[{'title': 'Community Amenities', 'value': ['L...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'tly11c8', 'RentalType': 1, 'Mo...","[2, 3]",40.12724,-88.28847,[],"[Laundry Facilities, Trash Pickup - Curbside, ...",1000,1.0,1.0
27,112 E. Green St by Bankier Apartments,112 E Green St Champaign IL 61820 US,Champaign,Campustown IL,800,850,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'zkmcc1x', 'RentalType': 1, 'Mo...",[2],40.11043,-88.23754,[],"[Fitness Center, Furnished Units Available, El...",905,1.0,1.0
28,Parkside,1205 E Florida Ave Urbana IL 61801 US,Urbana,,1080,1210,"[{'title': 'Apartment Features', 'value': ['Ai...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'jp2mpg7', 'RentalType': 1, 'Mo...",[2],40.09809,-88.19461,[],"[Air Conditioning, Dishwasher, Hardwood Floors...",1185,1.0,1.0
29,The Quarters,11 E Columbia Ave Champaign IL 61820 US,Champaign,Downtown Champaign,1325,1450,"[{'title': 'Community Amenities', 'value': ['F...","{'OneTimeBasics': [], 'UtilitiesAndEssentials'...","[{'RentalKey': '5fw7fcm', 'RentalType': 1, 'Mo...","[1, 2]",40.12090,-88.24280,[],"[Fitness Center, Laundry Facilities, Elevator,...",1430,1.0,1.0
30,Sterling on First,117 Sterling Ct Savoy IL 61874 US,Savoy,,1280,1529,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '0xrbf60', 'RentalType': 1, 'Mo...","[1, 2, 3, 4]",40.06769,-88.23921,[Utility Service Fee],"[Pool, Fitness Center, Laundry Facilities, Fur...",1385,1.0,3.0
31,Lancaster Apartments,112 E Chalmers St Champaign IL 61820 US,Champaign,Downtown Champaign,905,905,"[{'title': 'Community Amenities', 'value': ['L...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'mkjje2h', 'RentalType': 1, 'Mo...","[3, 4]",40.10672,-88.23714,[],"[Laundry Facilities, Furnished Units Available...",1010,1.0,2.0
32,THE ALCOVE @ SECOND & JOHN,202 E John St Champaign IL 61820 US,Champaign,Campustown IL,600,1350,"[{'title': 'Community Amenities', 'value': ['L...","{'OneTimeBasics': [], 'UtilitiesAndEssentials'...","[{'RentalKey': 'tdf187c', 'RentalType': 1, 'Mo...","[1, 2, 3]",40.10937,-88.23672,[],"[Laundry Facilities, Furnished Units Available...",705,1.0,1.0
33,Legacy202,202 E Daniel St Champaign IL 61820 US,Champaign,Campustown IL,1045,1975,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '8641h23', 'RentalType': 1, 'Mo...","[1, 2, 4]",40.10826,-88.23663,[Valet Trash],"[Fitness Center, Furnished Units Available, El...",1150,1.0,4.0
34,Seven07,707 S 4th St Champaign IL 61820 US,Champaign,Campustown IL,1089,2049,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '4s0vb8k', 'RentalType': 1, 'Mo...","[0, 1, 2, 3, 4]",40.10974,-88.23409,"[Utility - Water/Sewer, Utility - Electric]","[Pool, Fitness Center, Furnished Units Availab...",1194,1.0,4.0
35,200 Vine St,200 S Vine St Urbana IL 61802 US,Urbana,,1675,1675,[],"{'OneTimeBasics': [], 'UtilitiesAndEssentials'...","[{'RentalKey': '0066kv0', 'RentalType': 1, 'Mo...",[2],40.11137,-88.20476,[],[],1780,2.0,2.0
36,The Atrium,1306 N Lincoln Ave Urbana IL 61801 US,Urbana,,445,465,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '2hgvjp8', 'RentalType': 1, 'Mo...","[1, 4]",40.12443,-88.21819,[Utility Bundle],"[Pool, Fitness Center, Laundry Facilities, Fur...",550,1.0,4.0
37,907 Third,907 S 3rd St Champaign IL 61820 US,Champaign,Downtown Champaign,3125,3250,"[{'title': 'Community Amenities', 'value': ['W...","{'OneTimeBasics': [], 'UtilitiesAndEssentials'...","[{'RentalKey': 'v3jt79g', 'RentalType': 1, 'Mo...",[4],40.10733,-88.23567,[],"[Washer/Dryer, Air Conditioning, Dishwasher, H...",3230,2.0,2.0
38,Bailey Student Apartments Available 2026!,911 W Springfield Ave Urbana IL 61801 US,Urbana,,750,2080,"[{'title': 'Community Amenities', 'value': ['L...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'fh12k7s', 'RentalType': 1, 'Mo...","[1, 2, 3, 4]",40.11258,-88.22036,[],"[Laundry Facilities, Furnished Units Available...",855,1.0,2.0
39,The Hickory,513 N Hickory St Champaign IL 61820 US,Champaign,Downtown Champaign,1600,1600,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'yd9221r', 'RentalType': 1, 'Mo...",[2],40.12024,-88.24267,[],"[Fitness Center, Controlled Access, Recycling,...",1705,1.0,1.0
40,905 South Locust Street,905 S Locust St Champaign IL 61820 US,Champaign,Downtown Champaign,1195,1395,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'sf9rbl5', 'RentalType': 1, 'Mo...",[2],40.10729,-88.24056,[],"[Fitness Center, Recycling, Bicycle Storage, I...",1300,1.0,1.0
41,1107 S. Second St by Bankier Apartments,1107 S 2nd St Champaign IL 61820 US,Champaign,Downtown Champaign,3300,3300,"[{'title': 'Community Amenities', 'value': ['E...",None,"[{'RentalKey': 'nts6g0n', 'RentalType': 2, 'Mo...",[4],40.10459,-88.23785,[],"[Elevator, Clubhouse, Controlled Access, Key F...",3405,2.0,2.0
42,301 W. University Ave,301 W University Ave Champaign IL 61820 US,Champaign,Downtown Champaign,1250,1495,"[{'title': 'Community Amenities', 'value': ['W...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'mltlb4h', 'RentalType': 1, 'Mo...","[0, 1]",40.11605,-88.24702,[],"[Washer/Dryer, Air Conditioning, Dishwasher, H...",1355,1.0,1.0
43,314 S State St,314 S State St Champaign IL 61820 US,Champaign,Downtown Champaign,1450,1795,"[{'title': 'Community Amenities', 'value': ['W...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'ypnyegr', 'RentalType': 1, 'Mo...","[1, 2]",40.11313,-88.24652,[],"[Washer/Dryer, Air Conditioning, Dishwasher, H...",1555,1.0,2.0
44,305 W. Clark St,305 W Clark St Champaign IL 61820 US,Champaign,Downtown Champaign,1450,1795,"[{'title': 'Community Amenities', 'value': ['W...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'tck3658', 'RentalType': 1, 'Mo...","[1, 2]",40.11505,-88.24760,[],"[Washer/Dryer, Air Conditioning, Dishwasher, H...",1555,1.0,2.0
45,55 E Green St,55 E Green St Champaign IL 61820 US,Champaign,Campustown IL,1495,3500,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 'vebwzzd', 'RentalType': 1, 'Mo...","[1, 2, 3, 4]",40.10995,-88.23963,[],"[Furnished Units Available, Elevator, Fitness ...",1600,1.0,4.0
46,707 W Springfield Ave,707 W Springfield Ave Urbana IL 61801 US,Urbana,,1475,1845,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'dmyetwh', 'RentalType': 1, 'Mo...","[1, 2]",40.11263,-88.21695,[],"[Furnished Units Available, Elevator, Controll...",1580,1.0,1.0
47,Pfeffer Apartments - NOW LEASING AUGUST 2026,203 S 3rd St Champaign IL 61820 US,Champaign,Midtown Champaign,575,2400,"[{'title': 'Community Amenities', 'value': ['L...",None,"[{'RentalKey': 'gsrnlpz', 'RentalType': 1, 'Mo...","[1, 2, 3, 4]",40.11503,-88.23567,[],"[Laundry Facilities, Furnished Units Available...",680,1.0,2.0
48,Stone Ridge Square,1714 E Colorado Ave Urbana IL 61802 US,Urbana,,1175,1430,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '6y8gp7v', 'RentalType': 1, 'Mo...","[1, 2, 3]",40.09519,-88.18676,[],"[Pool, Fitness Center, Laundry Facilities, Pla...",1280,1.0,2.0
49,Fields South,3401 Fields South Dr Champaign IL 61822 US,Champaign,,1425,2150,"[{'title': 'Community Amenities', 'value': ['F...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '0lk7wk1', 'RentalType': 1, 'Mo...","[1, 2, 3]",40.07158,-88.31008,[],"[Fitness Center, Elevator, Recycling, Grill, W...",1530,1.0,2.0
50,410 E. Green St by Bankier Apartments,410 E Green St Champaign IL 61820 US,Champaign,,850,1650,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': '0zv9641', 'RentalType': 1, 'Mo...","[1, 2, 3]",40.11056,-88.23237,[],"[Fitness Center, Furnished Units Available, El...",955,1.0,2.0
51,Rally - Free Parking Included,305 E Clark St Champaign IL 61820 US,Champaign,Midtown Champaign,850,850,"[{'title': 'Apartment Features', 'value': ['Ai...",None,"[{'RentalKey': 'tlp4e5b', 'RentalType': 1, 'Mo...",[1],40.11510,-88.23470,[],"[Air Conditioning, High Speed Internet Access,...",955,1.0,1.0
52,Eastland Apartments,1905 N Cunningham Ave Urbana IL 61802 US,Urbana,,1025,1395,"[{'title': 'Community Amenities', 'value': ['P...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'kcbbgec', 'RentalType': 1, 'Mo...","[0, 2]",40.13082,-88.19984,[],"[Pool, Fitness Center, Laundry Facilities, 24 ...",1130,1.0,2.0
53,105 E Armory Ave,105 E Armory Ave Champaign IL 61820 US,Champaign,Downtown Champaign,1650,3800,"[{'title': 'Community Amenities', 'value': ['F...",None,"[{'RentalKey': 't5kxtzc', 'RentalType': 1, 'Mo...","[1, 2, 3, 4]",40.10509,-88.23795,[],"[Fitness Center, Elevator, Recycling, Walk To ...",1755,1.0,4.0
54,512 W Clark St,512 W Clark Champaign IL 61820 US,Champaign,Downtown Champaign,1465,1495,"[{'title': 'Community Amenities', 'value': ['W...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': 'gkbs5qw', 'RentalType': 1, 'Mo...",[1],40.11554,-88.25155,[],"[Washer/Dryer, Air Conditioning, Dishwasher, H...",1570,1.0,1.0
55,305 W Washington,305 W Washington St Champaign IL 61820 US,Champaign,Downtown Champaign,1495,1495,"[{'title': 'Community Amenities', 'value': ['W...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '9hk4546', 'RentalType': 1, 'Mo...",[1],40.11997,-88.24760,[],"[Washer/Dryer, Air Conditioning, Dishwasher, H...",1600,1.0,1.0
56,Castle Property Services,503 S Lynn St Champaign IL 61820 US,Champaign,Downtown Champaign,750,1400,"[{'title': 'Community Amenities', 'value': ['L...",{'OneTimeBasics': [{'ApartmentFeeCategoryId': ...,"[{'RentalKey': '2f0bc79', 'RentalType': 1, 'Mo...","[0, 1, 2]",40.11135,-88.25201,"[Utility - Water/Sewer, Trash and Recycling, R...","[Laundry Facilities, Furnished Units Available...",845,1.0,1.0